name: Automatic Rebase
on:
  push:
    branches:
      - develop

jobs:
  rebase:
    name: Rebase Next
    runs-on: ubuntu-latest
    steps:
      - name: Check out release/next
        uses: actions/checkout@v2
        with:
          ref: release/next
          fetch-depth: 0

      - name: Update release/next from upstream
        run: |
          git pull --rebase

      - name: User relative author
        run: |
          git config --global user.email ${{ github.event.pusher.email }} && git config --global user.name ${{ github.event.pusher.name }}

      - name: Try Rebase
        id: try-rebase
        run: |
          git rebase origin/develop

      - name: Push changes
        if: success() && ${{ steps.try-rebase.conclusion == 'success' }}
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/next
          force: true

      - name: Do this
        if: always()
        run: |
          echo ${{ steps.try-rebase.conclusion }} ${{ steps.try-rebase.conclusion == 'failure' }} failure()

      - name: Check out develop
        if: failure() && ${{ steps.try-rebase.conclusion == 'failure' }}
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0

      - name: Branchy
        if: failure() && ${{ steps.try-rebase.conclusion == 'failure' }}
        run: |
          git checkout -b reset/next-onto-develop origin/develop && git push origin HEAD --force

      - name: Create Pull Request
        if: failure() && ${{ steps.try-rebase.conclusion == 'failure' }}
        uses: thomaseizinger/create-pull-request@1dde00b9ad62f485245039414b37da2945d0e986
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: reset/next-onto-develop
          base: release/next
          title: '[Resolve] Develop -> Next'
          body: |
            ### :warning: Auto Rebase of Next with Develop failed :warning:

            - Please **merge in release/next** and resolve conflicts :smiley:
            - Auto-generated by [create-pull-request][1] within `auto-rebase.yml`

            [1]: https://github.com/thomaseizinger/create-pull-request@1dde00b9ad62f485245039414b37da2945d0e986
