name: Automatic Rebase
on:
  push:
    branches:
      - develop
jobs:
  rebase:
    name: Rebase Next
#    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          ref: 'release/next'
          fetch-depth: 0

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@b58fa7bac6d1d885234db03877f1d599c3ff48c7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
