name: Automatic Rebase
on:
  push:
    branches:
      - develop
jobs:
  rebase:
    name: Rebase Next
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest develop
        uses: actions/checkout@v2
        with:
          ref: 'develop'
          fetch-depth: 0

      - name: Checkout the latest next
        uses: actions/checkout@v2
        with:
          ref: 'release/next'
          fetch-depth: 0

      - name: Try Rebase
        if: success()
        run: |
          git rebase -i --root

      - name: Try Push
        if: success()
        run: |
          git push
