name: Automatic Rebase
on:
  push:
    branches:
      - develop

jobs:
  rebase:
    name: Rebase Next
    runs-on: ubuntu-latest
    steps:
      - name: Check out release/next
        uses: actions/checkout@v2
        with:
          ref: release/next
          fetch-depth: 0

      - name: Update release/next from upstream
        if: success()
        run: |
          git pull --rebase

      - name: User relative author
        if: success()
        run: |
          git config --global user.email ${{ github.event.pusher.email }} && git config --global user.name ${{ github.event.pusher.name }}

      - name: Try Rebase
        if: success()
        run: |
          git rebase origin/develop

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/next
          force: true

      - name: Check out develop
        if: failure()
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0

      - name: Branchy
        if: failure()
        run: |
          git checkout -b reset/next develop

      - name: Create Pull Request
        if: failure()
        uses: thomaseizinger/create-pull-request@1dde00b9ad62f485245039414b37da2945d0e986
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: release/next
          title: '[Resolve] Develop -> Next'

#      - name: Create Pull Request
#        if: failure()
#        uses: peter-evans/create-pull-request@40e70b8f7b4f2b5c96d75987c33edeb013cb81ab
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: Backfill Develop into Next
#          committer: GitHub <noreply@github.com>
#          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#          title: '[Backfill] Develop -> Next'
#          body: |
#            :warning: ### Auto Rebase of Next with Develop failed :warning:
#
#            - Please **rebase** Next and resolve conflicts manually :smiley:
#            - Auto-generated by [create-pull-request][1] within `auto-rebase.yml`
#
#            [1]: https://github.com/peter-evans/create-pull-request@40e70b8f7b4f2b5c96d75987c33edeb013cb81ab
#
#          branch: reset/next
#          base: release/next
#          labels: Release Approved :)
