name: Automatic Rebase
on:
  push:
    branches:
      - develop

jobs:
  rebase:
    name: Rebase Next
    runs-on: ubuntu-latest
    steps:

      - name: Check out release/next
        uses: actions/checkout@v2
        with:
          ref: release/next
          fetch-depth: 0

      - name: User relative author
        if: success()
        run: |
          git config --global user.email ${{ github.event.pusher.email }} && git config --global user.name ${{ github.event.pusher.name }}

      - name: Try Rebase
        if: success()
        run: |
          git rebase origin/develop

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/next
          force: true

      - name: Check out develop
        if: failure()
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0

      - name: Create Pull Request
        if: failure()
        uses: grassedge/git-pr-release-action@74169c50b9d00129f56a4b03b3309a2ab392f587
        with:
#          commit-message: Backfill Develop into Next
          owner: ${{ github.actor }} <${{ github.event.pusher.email }}>
#          title: '[Backfill] Develop -> Next'
#          body: |
#            :warning: ### Auto Rebase of Next with Develop failed :warning:
#
#            - Please **rebase** Next and resolve conflicts manually :smiley:
#            - Auto-generated by [create-pull-request][1] within `auto-rebase.yml`
#
#            [1]: https://github.com/peter-evans/create-pull-request@40e70b8f7b4f2b5c96d75987c33edeb013cb81ab
#
          token: ${{ secrets.GITHUB_TOKEN }}
          base: release/next
          head: develop
          labels: Release Approved :)
